#! ADD USER
// role : admin, user
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "user",
    "email": "user1@user1.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "user"
}


###
// fech all user
GET http://localhost:5000/users
###
// fech sigle user
GET http://localhost:5000/user/63bd702c512aae2b9648fe88
###
// edit user
PATCH http://localhost:5000/user/63a7dcff3e1c2260772c3c74
Content-Type: application/json

{
    "name": "Superadmin",
    "email": "admin@admin.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "admin"
}
###
// delete user
DELETE http://localhost:5000/user/63be4e2a09f0d969c921216f
###



#!AUTH ROUTE
// login 
#? admin login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "654321"
}
###
#? user login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "123456"
}
###
// verify
GET http://localhost:5000/verify
###
// logout
DELETE http://localhost:5000/logout
###


# !PRODUCT ROUTE
// get all product
GET http://localhost:5000/products
###
// create product
POST http://localhost:5000/product
Content-Type: application/json

{
    "title": "Laptop",
    "price": 20000000,
    "description": "Laptop gaming dengan kualitas"
}
###
// get one product
GET http://localhost:5000/product/63bbc64eaa14b7d2c88f41f3
###
// update product
PATCH http://localhost:5000/product/63a85f15ece106a25eec99cc
Content-Type: application/json

{
    "title": "Prosesor",
    "price": 5000000,
    "description": "Prosesor gaming dengan kualitas"
}
###
// delete product
DELETE http://localhost:5000/product/63a863dc1d7128d58af3be6d

###
// public route
GET http://localhost:5000/public/products