POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "user",
    "email": "user@user.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "user"
}

###
// fech all user
GET http://localhost:5000/users
###
// fech sigle user
GET http://localhost:5000/user/63a7dcff3e1c2260772c3c74
###
// edit user
PATCH http://localhost:5000/user/63a7dcff3e1c2260772c3c74
Content-Type: application/json

{
    "name": "Superadmin",
    "email": "admin@admin.com",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "admin"
}
###
// delete user
DELETE http://localhost:5000/user/63a7e1a23cae12741e23ed59

###
#!AUTH ROUTE
// login 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "123456"
}
###
// verify
GET http://localhost:5000/verify
###
// logout
DELETE http://localhost:5000/logout
###


# !PRODUCT ROUTE
// get all product
GET http://localhost:5000/products
###
// create product
POST http://localhost:5000/product
Content-Type: application/json

{
    "title": "Laptop",
    "price": 18000000,
    "description": "Laptop gaming dengan kualitas"
}
###
// get one product
GET http://localhost:5000/product/63a85f15ece106a25eec99cc
###
// update product
PATCH http://localhost:5000/product/63a85f15ece106a25eec99cc
Content-Type: application/json

{
    "title": "Prosesor",
    "price": 5000000,
    "description": "Prosesor gaming dengan kualitas"
}
###
// delete product
DELETE http://localhost:5000/product/63a863dc1d7128d58af3be6d